[project]
authors = ["Dan Allan <>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "garmin"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
download = "python download.py"
upload = "python upload.py"

[dependencies]
python = ">=3.13.1,<3.14"

[pypi-dependencies]
garminconnect = ">=0.2.25, <0.3"
garth = ">=0.5.2, <0.6"
requests = ">=2.32.3, <3"
readchar = ">=4.2.1, <5"
